# NumPy arrays

In [1]:
l = [1,2,3,4,5]

In [2]:
import numpy as np

In [3]:
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [6]:
l2 = [[1,2,3],[4,5,6],[7,8,9]] #nested lists

In [8]:
np.array(l2) #creates matrix as l2 is nested

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2) #start,end (not inclusive), step factor

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [13]:
#Return evenly spaced numbers over a specified interval
# start value,end value, number of points
#1d array
np.linspace(0,10,20)

array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])

In [14]:
np.linspace(0,15,30)

array([  0.        ,   0.51724138,   1.03448276,   1.55172414,
         2.06896552,   2.5862069 ,   3.10344828,   3.62068966,
         4.13793103,   4.65517241,   5.17241379,   5.68965517,
         6.20689655,   6.72413793,   7.24137931,   7.75862069,
         8.27586207,   8.79310345,   9.31034483,   9.82758621,
        10.34482759,  10.86206897,  11.37931034,  11.89655172,
        12.4137931 ,  12.93103448,  13.44827586,  13.96551724,
        14.48275862,  15.        ])

In [16]:
# identity matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [17]:
np.random.rand(10)

array([ 0.40462752,  0.04921009,  0.55535162,  0.75498202,  0.39383416,
        0.55732549,  0.30509141,  0.73981693,  0.06637972,  0.59897292])

In [18]:
np.random.rand(2,3)

array([[ 0.86270797,  0.0376702 ,  0.05276311],
       [ 0.59895768,  0.73545272,  0.41175325]])

In [19]:
# Return a sample (or samples) from the "standard normal" distributio
np.random.randn(2,3)

array([[-1.80839654, -1.5970036 , -0.57291885],
       [-0.84034392, -1.96857474,  1.29587382]])

In [20]:
np.random.randint(0,100,5)

array([90, 98, 30, 74, 53])

In [21]:
arr = np.arange(25)

In [22]:
rarr = np.random.randint(0,100,50)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
rarr

array([38, 99, 33, 64, 69, 17, 91, 43, 52, 76,  9, 68, 92, 55, 17, 16, 77,
       95, 16, 79, 93, 23, 72, 65,  0, 53,  4, 48, 26, 25, 64, 47, 92,  0,
       68, 56, 20, 66, 29, 18, 33, 28, 81, 12, 67, 28, 87, 38, 54, 47])

In [25]:
# Returns an array containing the same data with a new shape.
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
narr = arr.reshape(5,5)

In [28]:
narr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
narr.max()

24

In [30]:
narr.min()

0

In [31]:
narr.argmax()

24

In [32]:
narr.argmin()

0

In [34]:
narr.shape

(5, 5)

In [65]:
narr.dtype

dtype('int32')

### slicing and indexing

In [37]:
a = np.arange(0,11)

In [38]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
a[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
a[5:7]

array([5, 6])

In [42]:
a[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
a[5:]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
a[0:6] = 25

In [45]:
a

array([25, 25, 25, 25, 25, 25,  6,  7,  8,  9, 10])

In [48]:
arr2d = np.array([[12,45,78],[3,67,90],[34,1,23]])

In [49]:
arr2d

array([[12, 45, 78],
       [ 3, 67, 90],
       [34,  1, 23]])

In [50]:
arr2d[1][2]

90

In [51]:
arr2d[:2,1:] #top right corner

array([[45, 78],
       [67, 90]])

In [52]:
arr2d[1:,:2] #bottom left corner

array([[ 3, 67],
       [34,  1]])

In [53]:
arr2d[:1] #first row

array([[12, 45, 78]])

In [55]:
arr2d[:,:1] #first column

array([[12],
       [ 3],
       [34]])

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
arr > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [58]:
boolArr = arr >15

In [59]:
boolArr

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [60]:
arr[boolArr]

array([16, 17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
arr[arr>20]

array([21, 22, 23, 24])

In [62]:
twoD = np.arange(50).reshape(5,10)

In [63]:
twoD

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
twoD[1:3,3:5]

array([[13, 14],
       [23, 24]])

### Numpy operations

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [68]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [69]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [70]:
arr * arr #also element by element basis

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [71]:
arr - 20

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4])

In [72]:
1/0 #error

ZeroDivisionError: division by zero

In [73]:
arr / arr #first element is 0 but it throws warning and result is NaN

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.])

In [74]:
1 / arr #result is inf

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ,  0.09090909,  0.08333333,  0.07692308,  0.07142857,
        0.06666667,  0.0625    ,  0.05882353,  0.05555556,  0.05263158,
        0.05      ,  0.04761905,  0.04545455,  0.04347826,  0.04166667])

In [75]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [76]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949])

In [77]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
         1.62754791e+05,   4.42413392e+05,   1.20260428e+06,
         3.26901737e+06,   8.88611052e+06,   2.41549528e+07,
         6.56599691e+07,   1.78482301e+08,   4.85165195e+08,
         1.31881573e+09,   3.58491285e+09,   9.74480345e+09,
         2.64891221e+10])

In [78]:
arr.max()

24

In [79]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [81]:
np.log(arr) #warning again and result is -inf

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509,  2.39789527,  2.48490665,  2.56494936,  2.63905733,
        2.7080502 ,  2.77258872,  2.83321334,  2.89037176,  2.94443898,
        2.99573227,  3.04452244,  3.09104245,  3.13549422,  3.17805383])