NumPy arrays

In [1]:
l = [1,2,3,4,5]

In [2]:
import numpy as np

In [3]:
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [6]:
l2 = [[1,2,3],[4,5,6],[7,8,9]] #nested lists

In [8]:
np.array(l2) #creates matrix as l2 is nested

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2) #start,end (not inclusive), step factor

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [13]:
#Return evenly spaced numbers over a specified interval
# start value,end value, number of points
#1d array
np.linspace(0,10,20)

array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])

In [14]:
np.linspace(0,15,30)

array([  0.        ,   0.51724138,   1.03448276,   1.55172414,
         2.06896552,   2.5862069 ,   3.10344828,   3.62068966,
         4.13793103,   4.65517241,   5.17241379,   5.68965517,
         6.20689655,   6.72413793,   7.24137931,   7.75862069,
         8.27586207,   8.79310345,   9.31034483,   9.82758621,
        10.34482759,  10.86206897,  11.37931034,  11.89655172,
        12.4137931 ,  12.93103448,  13.44827586,  13.96551724,
        14.48275862,  15.        ])

In [16]:
# identity matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [17]:
np.random.rand(10)

array([ 0.40462752,  0.04921009,  0.55535162,  0.75498202,  0.39383416,
        0.55732549,  0.30509141,  0.73981693,  0.06637972,  0.59897292])

In [18]:
np.random.rand(2,3)

array([[ 0.86270797,  0.0376702 ,  0.05276311],
       [ 0.59895768,  0.73545272,  0.41175325]])

In [19]:
# Return a sample (or samples) from the "standard normal" distributio
np.random.randn(2,3)

array([[-1.80839654, -1.5970036 , -0.57291885],
       [-0.84034392, -1.96857474,  1.29587382]])

In [20]:
np.random.randint(0,100,5)

array([90, 98, 30, 74, 53])

In [21]:
arr = np.arange(25)

In [22]:
rarr = np.random.randint(0,100,50)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
rarr

array([38, 99, 33, 64, 69, 17, 91, 43, 52, 76,  9, 68, 92, 55, 17, 16, 77,
       95, 16, 79, 93, 23, 72, 65,  0, 53,  4, 48, 26, 25, 64, 47, 92,  0,
       68, 56, 20, 66, 29, 18, 33, 28, 81, 12, 67, 28, 87, 38, 54, 47])

In [25]:
# Returns an array containing the same data with a new shape.
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
narr = arr.reshape(5,5)

In [28]:
narr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
narr.max()

24

In [30]:
narr.min()

0

In [31]:
narr.argmax()

24

In [32]:
narr.argmin()

0

In [34]:
narr.shape

(5, 5)

In [35]:
narr.dtype

dtype('int32')

In [36]:
arr.dtype

dtype('int32')

In [37]:
a = np.arange(0,11)

In [38]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
a[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
a[5:7]

array([5, 6])

In [42]:
a[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
a[5:]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
a[0:6] = 25

In [45]:
a

array([25, 25, 25, 25, 25, 25,  6,  7,  8,  9, 10])

In [48]:
arr2d = np.array([[12,45,78],[3,67,90],[34,1,23]])

In [49]:
arr2d

array([[12, 45, 78],
       [ 3, 67, 90],
       [34,  1, 23]])

In [50]:
arr2d[1][2]

90

In [51]:
arr2d[:2,1:] #top right corner

array([[45, 78],
       [67, 90]])

In [52]:
arr2d[1:,:2] #bottom left corner

array([[ 3, 67],
       [34,  1]])

In [53]:
arr2d[:1] #first row

array([[12, 45, 78]])

In [55]:
arr2d[:,:1] #first column

array([[12],
       [ 3],
       [34]])

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
arr > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [58]:
boolArr = arr >15

In [59]:
boolArr

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [60]:
arr[boolArr]

array([16, 17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
arr[arr>20]

array([21, 22, 23, 24])

In [62]:
twoD = np.arange(50).reshape(5,10)

In [63]:
twoD

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
twoD[1:3,3:5]

array([[13, 14],
       [23, 24]])